### ISSUE TITLE
Zabbix agent unsafe user parameters

### ISSUE THREAD

**Issue by tkald** [zbx-sadman/unifi_proxy#1]
Document that in order get most of the data from unifi_proxy, zabbix_agentd.conf needs to have
UnsafeUserParameters**=1**
Many of the items otherwise become unsupported as many parameters are passed with quotes symbol:
e.g. `unifi.proxy[get,usergroup,default,"[_id=564c517ce4b07de37a55ff18].qos_rate_max_down"]`

**Comment by zbx-sadman** [comment]
Tanx for using UniFi Proxy, tkald.

Yes, Zabbix's directive _UnsafeUserParameters_ must be set to 1 for properly handling complex requests, which contain filters (with square brackets, logical and condition signs). But for simple using (taking values of _num_sta_ or _state_ keys) it's unnecessary. 

It's a Zabbix issue and resolved in Troubleshooting section of UniFi Miner guide, because Miner is forefather of Proxy. Both of utility use the same template, key format... I do not see any reason to duplicate the manual.

But i going to add link to Miner's Guide to Proxy's readme. 

Thank you for your comment.
