### ISSUE TITLE
Error Can't localte JSON.pm

### ISSUE THREAD

**Issue by luigdima** [zbx-sadman/unifi_proxy#12]
Hello!

When execute it the command 'unifi_proxy.pl' i returned this message:

```
root@zabbix:/# unifi_proxy.pl 
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/local/sbin/unifi_proxy.pl line 16.
BEGIN failed--compilation aborted at /usr/local/sbin/unifi_proxy.pl line 16.
```

I have already installed the packages:

`aptitude install libjson-xs-perl libwww-perl libio-socket-ssl-perl libdata-dumper-simple-perl libtime-hires-perl`

I need any more packages?

Thanks!! =)

**Comment by zbx-sadman** [comment]
Hello, Luis 

Thanks for question. I made an omission in the manual. Since v1.3.4 released you need to install [JSON wrapper module](https://metacpan.org/pod/JSON) to be able to choose between JSON packends (XS, PP or Cpanel). Just use `aptitude install libjson-perl` command.

You must see it in list of installed modules:
```
# dpkg --get-selections | grep libjson
libjson-perl                                      install
libjson-xs-perl                                   install
``` 
_libjson_ is an JSON wrapper and _libjson-xs_ is an fast JSON-backend.

**Comment by luigdima** [comment]
Hi!

Perfect! Already working =) thank you very much!

Solved!
