### ISSUE TITLE
Trigger $FW_UAP_LATEST_VER}

### ISSUE THREAD

**Issue by SeniorAnykey** [zbx-sadman/unifi_proxy#17]
After setting up the monitoring, this trigger worked, because the firmware version was obsolete. However, after updating the firmware at all the access point - it also hangs in the list of problems.

**Comment by zbx-sadman** [comment]
This trigger was not a very good idea, because Zabbix can compare only equivalence of string values.

UniFi Controller v5 (5.6 branch at least) have new feature - checking UniFi site for latest firmware. So, new template (\*UBNT_UniFi_UAP\*.xml) have trigger (will created from prototype while LLD processed) which detect "upgradable" state of UAP. It say to you that FW is not latest.

**Comment by zbx-sadman** [comment]
You can see trigger from new template (for UniFi Controller v5) working example:

``` 
    {...:unifi.proxy[get,uap,default,upgradable,5523fe519932508ffaf3b404,0].last()}=1
```

![image](https://user-images.githubusercontent.com/12827470/34242016-5df5a5da-e62a-11e7-8fae-e59d41b29c62.png)
