### ISSUE TITLE
Unifi Miner or Proxy for Zabbix

### ISSUE THREAD

**Issue by philthynz** [zbx-sadman/unifi_proxy#2]
What would you recommend if i wanted to pull metrics into Zabbix? Miner or Proxy. From reading your guide, Proxy is faster and less stress on the server?

**Comment by zbx-sadman** [comment]
Yes, it is. 

You can start with Miner, set up "Zabbix server  - Zabbix agent - Miner - UniFi controller" chain for proper interaction and then, if you need to more perfomance for more metrics fetching or your CPU became perspire, change Miner to Proxy because Proxy _so faster_ if used with Zabbix loadable modlue.

Miner is better for using for debug purposes and simple to integration. So, you do not need reconfigure Zabbix server when migrate from Miner to Proxy because both use the same Template.

**Comment by philthynz** [comment]
Great thanks
