### ISSUE TITLE
unifi.so make failed on debian stretch

### ISSUE THREAD

**Issue by PaulG4H** [zbx-sadman/unifi_proxy#22]
Hello,

I were able to compile the 
`gcc unifi_proxy_get.c -o unifi_proxy_get`
but when I try to run make within the zabbix 3 2 module there is an include missing which is not available in your git repo...

`/var/unifi_proxy/src/modules/zbx_unifi_Zabbix_3_2# ll

insgesamt 24

-rwxr-xr-x 1 root root   184 Jan 10 16:13 load.sh

-rw-r--r-- 1 root root    75 Jan 10 14:11 Makefile

-rw-r--r-- 1 root root 13282 Jan 10 14:11 unifi.c

root@paier-dl-service:/var/unifi_proxy/src/modules/zbx_unifi_Zabbix_3_2# make

gcc -fPIC -shared -o unifi.so unifi.c -I ../../../include

unifi.c:20:20: fatal error: sysinc.h: Datei oder Verzeichnis nicht gefunden

 #include "sysinc.h"

                    ^

compilation terminated.

Makefile:1: die Regel für Ziel „unifi“ scheiterte

make: *** [unifi] Fehler 1
`

Many thank's in advance for your support!
Paul

**Comment by zbx-sadman** [comment]
Hello, Paul.

You must follow installation procedure step by step (https://github.com/zbx-sadman/unifi_proxy/wiki/UniFi-Proxy-Guide-in-English -> Integration to monitoring system)

1. Download the source code Zabbix to linux box and unzip them;
2. Execute the ./configure command into Zabbix source tree without any options. Some program files that needed for further work must be created;
3. **Make directory src/modules/unifi into _the source tree_**;
4. Place to src/modules/unifi файлы Makefile and unifi.c files, that designed for your Zabbix release;
5. Run the make command in the newly created directory;
6. ...

Just find _src/module/dummy_ dir in source tree, create _unifi_ directory nearby and put _Makefile_ and _unifi.c_ into this dir. Then compile.

Do not use _/var/unifi_proxy/src/modules/zbx_unifi_Zabbix_3_2_. Compiler can't find Zabbix's include file _sysinc.h_ in _../../../include_ dir.

**Comment by PaulG4H** [comment]
Hello, 

many Thank's for the explanation, I downloaded the Source for Zabbix 3.4 and were able to compile the unifi.so module now, but Debian Stretch brings just Zabbix 3.07 and so the Agent throws the following Error:

> unsupported module "unifi.so" version: 2

Do I need to compile the Module with the sources from the Agent 3.07 or is there an other issue?

And the proxy is running (created an user zabbix in the controller and try to login with this credentials also without an issue in the web interface):

> netstat -tlnp|grep perl
> tcp        0      0 127.0.0.1:8448          0.0.0.0:*               LISTEN      27248/perl

but when I run the unifi_proxy_get as root I get nothing from the service:
> /usr/local/sbin/unifi_proxy_get 127.0.0.1 8448 "discovery,uap"
> {"data":[]}

Many thank's for your support in advance!

Paul

**Comment by zbx-sadman** [comment]
1)
Yes, since Zabbix 3.2 released, loadable module format changed.
Use https://github.com/zbx-sadman/unifi_proxy/tree/master/src/modules/zbx_unifi_Zabbix_3_0 for 3.0..3.1 branches
And https://github.com/zbx-sadman/unifi_proxy/tree/master/src/modules/zbx_unifi_Zabbix_3_2 for 3.2..3.4 branches.

2)
You can stop Unifi Proxy service, change debug level (via config file) and run script not in daemon mode (just run it from cli). Make query from additional session and see debug messages in first session.  Also, you can use UniFi Miner for testing (it have -d option) to get information directly from Controller. When you find problem and fix it, just jump to the Unifi Proxy.

**Comment by PaulG4H** [comment]
Many Thank's for your incredible fast and professional support!

Best regards
Peter

**Comment by PaulG4H** [comment]
@1 after download also the latest 3.0.14 Zabbix sources and ./configure and recompile the unifi.so the zabbix agend is starting without an issue

@2 With unifi_miner I figured out that the permission level in the unifi controller have to be "Super Administrator" otherwise I do not get any response, or is there maybe an other option available without granting this high Permissions to use it?

Best regards
Peter

**Comment by zbx-sadman** [comment]
On my UniFi Controller (5.5.20) i'll use _stat_ user:
```
admin                                      Super Administrator
stat	        noreply@mydomain.local	   Read Only
```

If you have more that one UniFi Site - you must create the same user on every site.

_admin_ account credientals used by Controller for access to UniFi devices via SSH. This is a reason to make other account, because for UniFi Proxy/Miner do not provide any protection for username/pass and they can be just sniffed on network. If you are not afraid it - you can use _admin_ account.

Honestly - there is a way to find out the administrator password using the read-only account, but it not so easy.
